/*
* generated by Xtext
*/
package com.euclideanspace.casl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.euclideanspace.casl.services.EditorGrammarAccess;

public class EditorParser extends AbstractContentAssistParser {
	
	@Inject
	private EditorGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.euclideanspace.casl.ui.contentassist.antlr.internal.InternalEditorParser createParser() {
		com.euclideanspace.casl.ui.contentassist.antlr.internal.InternalEditorParser result = new com.euclideanspace.casl.ui.contentassist.antlr.internal.InternalEditorParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getBasicSpecAccess().getAlternatives(), "rule__BasicSpec__Alternatives");
					put(grammarAccess.getBasicItemsAccess().getAlternatives(), "rule__BasicItems__Alternatives");
					put(grammarAccess.getBasicItemsAccess().getAlternatives_1_0_1(), "rule__BasicItems__Alternatives_1_0_1");
					put(grammarAccess.getBasicItemsAccess().getAlternatives_2_1(), "rule__BasicItems__Alternatives_2_1");
					put(grammarAccess.getBasicItemsAccess().getAlternatives_4_0(), "rule__BasicItems__Alternatives_4_0");
					put(grammarAccess.getSigItemsAccess().getAlternatives(), "rule__SigItems__Alternatives");
					put(grammarAccess.getSigItemsAccess().getAlternatives_0_0(), "rule__SigItems__Alternatives_0_0");
					put(grammarAccess.getSigItemsAccess().getAlternatives_1_0(), "rule__SigItems__Alternatives_1_0");
					put(grammarAccess.getSigItemsAccess().getAlternatives_2_0(), "rule__SigItems__Alternatives_2_0");
					put(grammarAccess.getSigItemsAccess().getAlternatives_3_0(), "rule__SigItems__Alternatives_3_0");
					put(grammarAccess.getOpItemAccess().getAlternatives(), "rule__OpItem__Alternatives");
					put(grammarAccess.getOpTypeAccess().getAlternatives(), "rule__OpType__Alternatives");
					put(grammarAccess.getOpAttrAccess().getAlternatives(), "rule__OpAttr__Alternatives");
					put(grammarAccess.getOpHeadAccess().getAlternatives(), "rule__OpHead__Alternatives");
					put(grammarAccess.getPredItemAccess().getAlternatives(), "rule__PredItem__Alternatives");
					put(grammarAccess.getPredTypeAccess().getAlternatives(), "rule__PredType__Alternatives");
					put(grammarAccess.getFormulaUnaryAccess().getAlternatives(), "rule__FormulaUnary__Alternatives");
					put(grammarAccess.getQuantifierAccess().getAlternatives(), "rule__Quantifier__Alternatives");
					put(grammarAccess.getMisfixUnaryAccess().getAlternatives(), "rule__MisfixUnary__Alternatives");
					put(grammarAccess.getTokenAccess().getAlternatives(), "rule__Token__Alternatives");
					put(grammarAccess.getBasicSpecAccess().getGroup_1(), "rule__BasicSpec__Group_1__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_1(), "rule__BasicItems__Group_1__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_1_0(), "rule__BasicItems__Group_1_0__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_1_0_3(), "rule__BasicItems__Group_1_0_3__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_2(), "rule__BasicItems__Group_2__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_2_3(), "rule__BasicItems__Group_2_3__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_3(), "rule__BasicItems__Group_3__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_4(), "rule__BasicItems__Group_4__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_4_2(), "rule__BasicItems__Group_4_2__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_5(), "rule__BasicItems__Group_5__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_5_2(), "rule__BasicItems__Group_5_2__0");
					put(grammarAccess.getBasicItemsAccess().getGroup_5_5(), "rule__BasicItems__Group_5_5__0");
					put(grammarAccess.getSigItemsAccess().getGroup_0(), "rule__SigItems__Group_0__0");
					put(grammarAccess.getSigItemsAccess().getGroup_0_2(), "rule__SigItems__Group_0_2__0");
					put(grammarAccess.getSigItemsAccess().getGroup_1(), "rule__SigItems__Group_1__0");
					put(grammarAccess.getSigItemsAccess().getGroup_1_2(), "rule__SigItems__Group_1_2__0");
					put(grammarAccess.getSigItemsAccess().getGroup_2(), "rule__SigItems__Group_2__0");
					put(grammarAccess.getSigItemsAccess().getGroup_2_2(), "rule__SigItems__Group_2_2__0");
					put(grammarAccess.getSigItemsAccess().getGroup_3(), "rule__SigItems__Group_3__0");
					put(grammarAccess.getSigItemsAccess().getGroup_3_2(), "rule__SigItems__Group_3_2__0");
					put(grammarAccess.getSortItemAccess().getGroup(), "rule__SortItem__Group__0");
					put(grammarAccess.getSortItemAccess().getGroup_1(), "rule__SortItem__Group_1__0");
					put(grammarAccess.getOpItemAccess().getGroup_0(), "rule__OpItem__Group_0__0");
					put(grammarAccess.getOpItemAccess().getGroup_0_1(), "rule__OpItem__Group_0_1__0");
					put(grammarAccess.getOpItemAccess().getGroup_0_4(), "rule__OpItem__Group_0_4__0");
					put(grammarAccess.getOpItemAccess().getGroup_1(), "rule__OpItem__Group_1__0");
					put(grammarAccess.getOpTypeAccess().getGroup_0(), "rule__OpType__Group_0__0");
					put(grammarAccess.getOpTypeAccess().getGroup_1(), "rule__OpType__Group_1__0");
					put(grammarAccess.getOpTypeAccess().getGroup_1_1(), "rule__OpType__Group_1_1__0");
					put(grammarAccess.getOpAttrAccess().getGroup_3(), "rule__OpAttr__Group_3__0");
					put(grammarAccess.getOpHeadAccess().getGroup_0(), "rule__OpHead__Group_0__0");
					put(grammarAccess.getOpHeadAccess().getGroup_1(), "rule__OpHead__Group_1__0");
					put(grammarAccess.getOpHeadAccess().getGroup_1_1(), "rule__OpHead__Group_1_1__0");
					put(grammarAccess.getArgDeclAccess().getGroup(), "rule__ArgDecl__Group__0");
					put(grammarAccess.getArgDeclAccess().getGroup_1(), "rule__ArgDecl__Group_1__0");
					put(grammarAccess.getPredItemAccess().getGroup_0(), "rule__PredItem__Group_0__0");
					put(grammarAccess.getPredItemAccess().getGroup_0_1(), "rule__PredItem__Group_0_1__0");
					put(grammarAccess.getPredItemAccess().getGroup_1(), "rule__PredItem__Group_1__0");
					put(grammarAccess.getPredTypeAccess().getGroup_0(), "rule__PredType__Group_0__0");
					put(grammarAccess.getPredTypeAccess().getGroup_0_1(), "rule__PredType__Group_0_1__0");
					put(grammarAccess.getPredTypeAccess().getGroup_1(), "rule__PredType__Group_1__0");
					put(grammarAccess.getPredHeadAccess().getGroup(), "rule__PredHead__Group__0");
					put(grammarAccess.getPredHeadAccess().getGroup_1(), "rule__PredHead__Group_1__0");
					put(grammarAccess.getDatatypeDeclAccess().getGroup(), "rule__DatatypeDecl__Group__0");
					put(grammarAccess.getDatatypeDeclAccess().getGroup_3(), "rule__DatatypeDecl__Group_3__0");
					put(grammarAccess.getAlternativeAccess().getGroup(), "rule__Alternative__Group__0");
					put(grammarAccess.getAlternativeAccess().getGroup_1(), "rule__Alternative__Group_1__0");
					put(grammarAccess.getAlternativeAccess().getGroup_1_1(), "rule__Alternative__Group_1_1__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getComponentAccess().getGroup_0(), "rule__Component__Group_0__0");
					put(grammarAccess.getComponentAccess().getGroup_0_1(), "rule__Component__Group_0_1__0");
					put(grammarAccess.getVarDeclAccess().getGroup(), "rule__VarDecl__Group__0");
					put(grammarAccess.getVarDeclAccess().getGroup_1(), "rule__VarDecl__Group_1__0");
					put(grammarAccess.getFormulaAndAccess().getGroup(), "rule__FormulaAnd__Group__0");
					put(grammarAccess.getFormulaAndAccess().getGroup_1(), "rule__FormulaAnd__Group_1__0");
					put(grammarAccess.getFormulaOrAccess().getGroup(), "rule__FormulaOr__Group__0");
					put(grammarAccess.getFormulaOrAccess().getGroup_1(), "rule__FormulaOr__Group_1__0");
					put(grammarAccess.getFormulaImpliesAccess().getGroup(), "rule__FormulaImplies__Group__0");
					put(grammarAccess.getFormulaImpliesAccess().getGroup_1(), "rule__FormulaImplies__Group_1__0");
					put(grammarAccess.getFormulaIfAccess().getGroup(), "rule__FormulaIf__Group__0");
					put(grammarAccess.getFormulaIfAccess().getGroup_1(), "rule__FormulaIf__Group_1__0");
					put(grammarAccess.getFormulaEquivAccess().getGroup(), "rule__FormulaEquiv__Group__0");
					put(grammarAccess.getFormulaEquivAccess().getGroup_1(), "rule__FormulaEquiv__Group_1__0");
					put(grammarAccess.getFormulaUnaryAccess().getGroup_2(), "rule__FormulaUnary__Group_2__0");
					put(grammarAccess.getFormulaUnaryAccess().getGroup_3(), "rule__FormulaUnary__Group_3__0");
					put(grammarAccess.getTermsAccess().getGroup(), "rule__Terms__Group__0");
					put(grammarAccess.getTermsAccess().getGroup_1(), "rule__Terms__Group_1__0");
					put(grammarAccess.getTermAccess().getGroup(), "rule__Term__Group__0");
					put(grammarAccess.getMisfixAccess().getGroup(), "rule__Misfix__Group__0");
					put(grammarAccess.getMisfixAccess().getGroup_1(), "rule__Misfix__Group_1__0");
					put(grammarAccess.getMisfixUnaryAccess().getGroup_0(), "rule__MisfixUnary__Group_0__0");
					put(grammarAccess.getMisfixUnaryAccess().getGroup_1(), "rule__MisfixUnary__Group_1__0");
					put(grammarAccess.getMisfixUnaryAccess().getGroup_2(), "rule__MisfixUnary__Group_2__0");
					put(grammarAccess.getMisfixUnaryAccess().getGroup_9(), "rule__MisfixUnary__Group_9__0");
					put(grammarAccess.getMisfixUnaryAccess().getGroup_10(), "rule__MisfixUnary__Group_10__0");
					put(grammarAccess.getQualPredNameAccess().getGroup(), "rule__QualPredName__Group__0");
					put(grammarAccess.getQualVarNameAccess().getGroup(), "rule__QualVarName__Group__0");
					put(grammarAccess.getQualOpNameAccess().getGroup(), "rule__QualOpName__Group__0");
					put(grammarAccess.getTokenAccess().getGroup_2(), "rule__Token__Group_2__0");
					put(grammarAccess.getModelAccess().getBasicSpecAssignment(), "rule__Model__BasicSpecAssignment");
					put(grammarAccess.getBasicSpecAccess().getBasicItemsAssignment_0(), "rule__BasicSpec__BasicItemsAssignment_0");
					put(grammarAccess.getBasicSpecAccess().getEmptyAssignment_1_0(), "rule__BasicSpec__EmptyAssignment_1_0");
					put(grammarAccess.getBasicItemsAccess().getSAssignment_0(), "rule__BasicItems__SAssignment_0");
					put(grammarAccess.getBasicItemsAccess().getDatatypeDeclAssignment_1_0_2(), "rule__BasicItems__DatatypeDeclAssignment_1_0_2");
					put(grammarAccess.getBasicItemsAccess().getDatatypeDecl2Assignment_1_0_3_1(), "rule__BasicItems__DatatypeDecl2Assignment_1_0_3_1");
					put(grammarAccess.getBasicItemsAccess().getDatatypeDeclAssignment_2_2(), "rule__BasicItems__DatatypeDeclAssignment_2_2");
					put(grammarAccess.getBasicItemsAccess().getDatatypeDecl2Assignment_2_3_1(), "rule__BasicItems__DatatypeDecl2Assignment_2_3_1");
					put(grammarAccess.getBasicItemsAccess().getS2Assignment_3_2(), "rule__BasicItems__S2Assignment_3_2");
					put(grammarAccess.getBasicItemsAccess().getVarDeclAssignment_4_1(), "rule__BasicItems__VarDeclAssignment_4_1");
					put(grammarAccess.getBasicItemsAccess().getVarDecl2Assignment_4_2_1(), "rule__BasicItems__VarDecl2Assignment_4_2_1");
					put(grammarAccess.getBasicItemsAccess().getVarDeclAssignment_5_1(), "rule__BasicItems__VarDeclAssignment_5_1");
					put(grammarAccess.getBasicItemsAccess().getVarDecl2Assignment_5_2_1(), "rule__BasicItems__VarDecl2Assignment_5_2_1");
					put(grammarAccess.getBasicItemsAccess().getFormulaAssignment_5_4(), "rule__BasicItems__FormulaAssignment_5_4");
					put(grammarAccess.getBasicItemsAccess().getFormula2Assignment_5_5_1(), "rule__BasicItems__Formula2Assignment_5_5_1");
					put(grammarAccess.getSigItemsAccess().getSortItemAssignment_0_1(), "rule__SigItems__SortItemAssignment_0_1");
					put(grammarAccess.getSigItemsAccess().getSortItem2Assignment_0_2_1(), "rule__SigItems__SortItem2Assignment_0_2_1");
					put(grammarAccess.getSigItemsAccess().getOpItemAssignment_1_1(), "rule__SigItems__OpItemAssignment_1_1");
					put(grammarAccess.getSigItemsAccess().getOpItem2Assignment_1_2_1(), "rule__SigItems__OpItem2Assignment_1_2_1");
					put(grammarAccess.getSigItemsAccess().getPredItemAssignment_2_1(), "rule__SigItems__PredItemAssignment_2_1");
					put(grammarAccess.getSigItemsAccess().getPredItem2Assignment_2_2_1(), "rule__SigItems__PredItem2Assignment_2_2_1");
					put(grammarAccess.getSigItemsAccess().getDatatypeDeclAssignment_3_1(), "rule__SigItems__DatatypeDeclAssignment_3_1");
					put(grammarAccess.getSigItemsAccess().getDatatypeDecl2Assignment_3_2_1(), "rule__SigItems__DatatypeDecl2Assignment_3_2_1");
					put(grammarAccess.getSortItemAccess().getSortAssignment_0(), "rule__SortItem__SortAssignment_0");
					put(grammarAccess.getSortItemAccess().getSort2Assignment_1_1(), "rule__SortItem__Sort2Assignment_1_1");
					put(grammarAccess.getOpItemAccess().getOpNameAssignment_0_0(), "rule__OpItem__OpNameAssignment_0_0");
					put(grammarAccess.getOpItemAccess().getOpName2Assignment_0_1_1(), "rule__OpItem__OpName2Assignment_0_1_1");
					put(grammarAccess.getOpItemAccess().getOpTypeAssignment_0_3(), "rule__OpItem__OpTypeAssignment_0_3");
					put(grammarAccess.getOpItemAccess().getOpAttrAssignment_0_4_1(), "rule__OpItem__OpAttrAssignment_0_4_1");
					put(grammarAccess.getOpItemAccess().getOpNameAssignment_1_0(), "rule__OpItem__OpNameAssignment_1_0");
					put(grammarAccess.getOpItemAccess().getOpHeadAssignment_1_1(), "rule__OpItem__OpHeadAssignment_1_1");
					put(grammarAccess.getOpItemAccess().getTermAssignment_1_3(), "rule__OpItem__TermAssignment_1_3");
					put(grammarAccess.getOpTypeAccess().getSortAssignment_0_1(), "rule__OpType__SortAssignment_0_1");
					put(grammarAccess.getOpTypeAccess().getSortAssignment_1_0(), "rule__OpType__SortAssignment_1_0");
					put(grammarAccess.getOpTypeAccess().getSort2Assignment_1_1_1(), "rule__OpType__Sort2Assignment_1_1_1");
					put(grammarAccess.getOpTypeAccess().getSort3Assignment_1_4(), "rule__OpType__Sort3Assignment_1_4");
					put(grammarAccess.getOpAttrAccess().getOpAssignment_0(), "rule__OpAttr__OpAssignment_0");
					put(grammarAccess.getOpAttrAccess().getOpAssignment_1(), "rule__OpAttr__OpAssignment_1");
					put(grammarAccess.getOpAttrAccess().getOpAssignment_2(), "rule__OpAttr__OpAssignment_2");
					put(grammarAccess.getOpAttrAccess().getOpAssignment_3_0(), "rule__OpAttr__OpAssignment_3_0");
					put(grammarAccess.getOpAttrAccess().getTermAssignment_3_1(), "rule__OpAttr__TermAssignment_3_1");
					put(grammarAccess.getOpHeadAccess().getSortAssignment_0_2(), "rule__OpHead__SortAssignment_0_2");
					put(grammarAccess.getOpHeadAccess().getArgDeclAssignment_1_0(), "rule__OpHead__ArgDeclAssignment_1_0");
					put(grammarAccess.getOpHeadAccess().getArgDecl2Assignment_1_1_1(), "rule__OpHead__ArgDecl2Assignment_1_1_1");
					put(grammarAccess.getOpHeadAccess().getSortAssignment_1_4(), "rule__OpHead__SortAssignment_1_4");
					put(grammarAccess.getArgDeclAccess().getVarAssignment_0(), "rule__ArgDecl__VarAssignment_0");
					put(grammarAccess.getArgDeclAccess().getVar2Assignment_1_1(), "rule__ArgDecl__Var2Assignment_1_1");
					put(grammarAccess.getArgDeclAccess().getSortAssignment_3(), "rule__ArgDecl__SortAssignment_3");
					put(grammarAccess.getPredItemAccess().getPredNameAssignment_0_0(), "rule__PredItem__PredNameAssignment_0_0");
					put(grammarAccess.getPredItemAccess().getPredName2Assignment_0_1_1(), "rule__PredItem__PredName2Assignment_0_1_1");
					put(grammarAccess.getPredItemAccess().getPredTypeAssignment_0_3(), "rule__PredItem__PredTypeAssignment_0_3");
					put(grammarAccess.getPredItemAccess().getPredNameAssignment_1_0(), "rule__PredItem__PredNameAssignment_1_0");
					put(grammarAccess.getPredItemAccess().getPredHeadAssignment_1_1(), "rule__PredItem__PredHeadAssignment_1_1");
					put(grammarAccess.getPredItemAccess().getFormulaAssignment_1_3(), "rule__PredItem__FormulaAssignment_1_3");
					put(grammarAccess.getPredTypeAccess().getSortAssignment_0_0(), "rule__PredType__SortAssignment_0_0");
					put(grammarAccess.getPredTypeAccess().getSort2Assignment_0_1_1(), "rule__PredType__Sort2Assignment_0_1_1");
					put(grammarAccess.getPredTypeAccess().getBAssignment_1_0(), "rule__PredType__BAssignment_1_0");
					put(grammarAccess.getPredHeadAccess().getArgDeclAssignment_0(), "rule__PredHead__ArgDeclAssignment_0");
					put(grammarAccess.getPredHeadAccess().getArgDecl2Assignment_1_1(), "rule__PredHead__ArgDecl2Assignment_1_1");
					put(grammarAccess.getDatatypeDeclAccess().getAlternativeAssignment_2(), "rule__DatatypeDecl__AlternativeAssignment_2");
					put(grammarAccess.getDatatypeDeclAccess().getAlternative2Assignment_3_1(), "rule__DatatypeDecl__Alternative2Assignment_3_1");
					put(grammarAccess.getAlternativeAccess().getOpNameAssignment_0(), "rule__Alternative__OpNameAssignment_0");
					put(grammarAccess.getAlternativeAccess().getComponentAssignment_1_0(), "rule__Alternative__ComponentAssignment_1_0");
					put(grammarAccess.getAlternativeAccess().getComponent2Assignment_1_1_1(), "rule__Alternative__Component2Assignment_1_1_1");
					put(grammarAccess.getComponentAccess().getOpNameAssignment_0_0(), "rule__Component__OpNameAssignment_0_0");
					put(grammarAccess.getComponentAccess().getOpName2Assignment_0_1_1(), "rule__Component__OpName2Assignment_0_1_1");
					put(grammarAccess.getComponentAccess().getSortAssignment_1(), "rule__Component__SortAssignment_1");
					put(grammarAccess.getVarDeclAccess().getVarAssignment_0(), "rule__VarDecl__VarAssignment_0");
					put(grammarAccess.getVarDeclAccess().getVar2Assignment_1_1(), "rule__VarDecl__Var2Assignment_1_1");
					put(grammarAccess.getVarDeclAccess().getSortAssignment_3(), "rule__VarDecl__SortAssignment_3");
					put(grammarAccess.getFormulaAccess().getFormulaAssignment(), "rule__Formula__FormulaAssignment");
					put(grammarAccess.getFormulaAndAccess().getOpAssignment_1_1(), "rule__FormulaAnd__OpAssignment_1_1");
					put(grammarAccess.getFormulaAndAccess().getRightAssignment_1_2(), "rule__FormulaAnd__RightAssignment_1_2");
					put(grammarAccess.getFormulaOrAccess().getOpAssignment_1_1(), "rule__FormulaOr__OpAssignment_1_1");
					put(grammarAccess.getFormulaOrAccess().getRightAssignment_1_2(), "rule__FormulaOr__RightAssignment_1_2");
					put(grammarAccess.getFormulaImpliesAccess().getOpAssignment_1_1(), "rule__FormulaImplies__OpAssignment_1_1");
					put(grammarAccess.getFormulaImpliesAccess().getRightAssignment_1_2(), "rule__FormulaImplies__RightAssignment_1_2");
					put(grammarAccess.getFormulaIfAccess().getOpAssignment_1_1(), "rule__FormulaIf__OpAssignment_1_1");
					put(grammarAccess.getFormulaIfAccess().getRightAssignment_1_2(), "rule__FormulaIf__RightAssignment_1_2");
					put(grammarAccess.getFormulaEquivAccess().getOpAssignment_1_1(), "rule__FormulaEquiv__OpAssignment_1_1");
					put(grammarAccess.getFormulaEquivAccess().getRightAssignment_1_2(), "rule__FormulaEquiv__RightAssignment_1_2");
					put(grammarAccess.getFormulaUnaryAccess().getE3Assignment_0(), "rule__FormulaUnary__E3Assignment_0");
					put(grammarAccess.getFormulaUnaryAccess().getE3Assignment_1(), "rule__FormulaUnary__E3Assignment_1");
					put(grammarAccess.getFormulaUnaryAccess().getE3Assignment_2_0(), "rule__FormulaUnary__E3Assignment_2_0");
					put(grammarAccess.getFormulaUnaryAccess().getTAssignment_2_1(), "rule__FormulaUnary__TAssignment_2_1");
					put(grammarAccess.getFormulaUnaryAccess().getTAssignment_3_0(), "rule__FormulaUnary__TAssignment_3_0");
					put(grammarAccess.getFormulaUnaryAccess().getE3Assignment_3_1(), "rule__FormulaUnary__E3Assignment_3_1");
					put(grammarAccess.getFormulaUnaryAccess().getT2Assignment_3_2(), "rule__FormulaUnary__T2Assignment_3_2");
					put(grammarAccess.getQuantifierAccess().getQAssignment_0(), "rule__Quantifier__QAssignment_0");
					put(grammarAccess.getQuantifierAccess().getQAssignment_1(), "rule__Quantifier__QAssignment_1");
					put(grammarAccess.getQuantifierAccess().getQAssignment_2(), "rule__Quantifier__QAssignment_2");
					put(grammarAccess.getTermsAccess().getTermAssignment_0(), "rule__Terms__TermAssignment_0");
					put(grammarAccess.getTermsAccess().getTerm2Assignment_1_1(), "rule__Terms__Term2Assignment_1_1");
					put(grammarAccess.getTermAccess().getMisfixAssignment_0(), "rule__Term__MisfixAssignment_0");
					put(grammarAccess.getTermAccess().getMisfix2Assignment_1(), "rule__Term__Misfix2Assignment_1");
					put(grammarAccess.getMisfixAccess().getOpAssignment_1_1(), "rule__Misfix__OpAssignment_1_1");
					put(grammarAccess.getMisfixAccess().getSortAssignment_1_2(), "rule__Misfix__SortAssignment_1_2");
					put(grammarAccess.getMisfixUnaryAccess().getMisfixAssignment_0_1(), "rule__MisfixUnary__MisfixAssignment_0_1");
					put(grammarAccess.getMisfixUnaryAccess().getMisfixAssignment_1_1(), "rule__MisfixUnary__MisfixAssignment_1_1");
					put(grammarAccess.getMisfixUnaryAccess().getMisfixAssignment_2_1(), "rule__MisfixUnary__MisfixAssignment_2_1");
					put(grammarAccess.getMisfixUnaryAccess().getOp1Assignment_3(), "rule__MisfixUnary__Op1Assignment_3");
					put(grammarAccess.getMisfixUnaryAccess().getOp2Assignment_4(), "rule__MisfixUnary__Op2Assignment_4");
					put(grammarAccess.getMisfixUnaryAccess().getOp3Assignment_5(), "rule__MisfixUnary__Op3Assignment_5");
					put(grammarAccess.getMisfixUnaryAccess().getOp4Assignment_6(), "rule__MisfixUnary__Op4Assignment_6");
					put(grammarAccess.getMisfixUnaryAccess().getOp5Assignment_7(), "rule__MisfixUnary__Op5Assignment_7");
					put(grammarAccess.getMisfixUnaryAccess().getOp6Assignment_8(), "rule__MisfixUnary__Op6Assignment_8");
					put(grammarAccess.getMisfixUnaryAccess().getOpAssignment_9_0(), "rule__MisfixUnary__OpAssignment_9_0");
					put(grammarAccess.getMisfixUnaryAccess().getOpAssignment_10_0(), "rule__MisfixUnary__OpAssignment_10_0");
					put(grammarAccess.getQualPredNameAccess().getSortAssignment_4(), "rule__QualPredName__SortAssignment_4");
					put(grammarAccess.getQualVarNameAccess().getPredTypeAssignment_4(), "rule__QualVarName__PredTypeAssignment_4");
					put(grammarAccess.getQualOpNameAccess().getOpTypeAssignment_4(), "rule__QualOpName__OpTypeAssignment_4");
					put(grammarAccess.getSortAccess().getNameAssignment(), "rule__Sort__NameAssignment");
					put(grammarAccess.getOpNameAccess().getNameAssignment(), "rule__OpName__NameAssignment");
					put(grammarAccess.getPredNameAccess().getNameAssignment(), "rule__PredName__NameAssignment");
					put(grammarAccess.getVarAccess().getNameAssignment(), "rule__Var__NameAssignment");
					put(grammarAccess.getTokenAccess().getNameAssignment_0(), "rule__Token__NameAssignment_0");
					put(grammarAccess.getTokenAccess().getNumAssignment_1(), "rule__Token__NumAssignment_1");
					put(grammarAccess.getTokenAccess().getNameAssignment_2_0(), "rule__Token__NameAssignment_2_0");
					put(grammarAccess.getTokenAccess().getTAssignment_2_2(), "rule__Token__TAssignment_2_2");
					put(grammarAccess.getLiteralAccess().getStrAssignment(), "rule__Literal__StrAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.euclideanspace.casl.ui.contentassist.antlr.internal.InternalEditorParser typedParser = (com.euclideanspace.casl.ui.contentassist.antlr.internal.InternalEditorParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] {  };
	}
	
	public EditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
