/*
 * generated by Xtext
 */
package com.euclideanspace.casl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EditorRuntimeModule extends com.euclideanspace.casl.AbstractEditorRuntimeModule {

}
